apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-pg-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pg
  template:
    metadata:
      labels:
        app: auth-pg
    spec:
      containers:
        - name: auth-pg
          image: postgres
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: auth
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD


---
apiVersion: v1
kind: Service
metadata:
  name: auth-pg-srv
spec:
  selector:
    app: auth-pg
  ports:
    - name: auth-pg
      protocol: TCP
      port: 5432
      targetPort: 5432
