apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres
          imagePullPolicy: IfNotPresent
          command: [
              "sh",
              "-c",
              "until pg_isready -h auth-pg-srv -p 5432;
              do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: auth
          image: hmdrzadev/auth
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
