apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded

spec:
  backoffLimit: 1
  template:
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres
          imagePullPolicy: IfNotPresent
          command: [
              "sh",
              "-c",
              "until pg_isready -h auth-pg-srv -p 5432;
              do echo waiting for database; sleep 2; done;",
            ]
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: hmdrzadev/auth
          imagePullPolicy: IfNotPresent
          command: ["yarn", "migrate"]
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: POSTGRES_PASSWORD
